<?php

$_category_desc = $this->helper('Smartwave\Porto\Helper\Data')->getConfig('porto_settings/category/category_description');

?>
<?php if ($_category_desc == "main_column" && $_annotation = $block->getCurrentCategory()->getVpAnnotation()) : ?>
    <div class="category-annotation">
        <?php echo $this->helper('Magento\Catalog\Helper\Output')->categoryAttribute($block->getCurrentCategory(), $_annotation, 'description') ?>
    </div>
<?php endif; ?>
