<?php

$_category_desc = $this->helper('Smartwave\Porto\Helper\Data')->getConfig('porto_settings/category/category_description');

?>
<?php if ($_category_desc == "main_column" && $_description = $block->getCurrentCategory()->getDescription()): ?>
    <div class="category-description">
        <?php echo $this->helper('Magento\Catalog\Helper\Output')->categoryAttribute($block->getCurrentCategory(), $_description, 'description') ?>
        <a href="javascript:void(0)" class="more">Подробнее</a>
        <a href="javascript:void(0)" class="less" style="display: none">Меньше</a>
    </div>
    <script type="text/javascript">
        requirejs(['jquery', 'Magento_Catalog/js/jquery.dotdotdot.min'], function($) {
            var h = 150;
            if ($('div.category-description>p').length > 0) {
                var ch = $($('div.category-description>p')[0]).height() + 50;
                if (ch > h) h = ch;
            }
            $("div.category-description").dotdotdot({
                wrap: 'children',
                height: h,
                after: 'a.more',
                callback: dotdotdotCallback
            });
            $("div.category-description").on('click', 'a', function() {
                var div = $(this).closest('div.category-description');
                if ($(this).text() == "Подробнее") {
                    div.trigger('destroy').find('a.more').hide();
                    div.css('max-height', '');
                    $("a.less", div).show();
                } else {
                    $(this).closest('div.category-description').css("max-height", ""+h+"px").dotdotdot({
                        wrap: 'children',
                        height: h,
                        after: "a.more",
                        callback: dotdotdotCallback
                    });
                    $("a.less", div).hide();
                }
            });

            function dotdotdotCallback(isTruncated, originalContent) {
                if (!isTruncated) {
                    $("a", this).remove();
                }
            }
        });
    </script>
<?php endif; ?>
