<?php

$_category_desc = $this->helper('Smartwave\Porto\Helper\Data')->getConfig('porto_settings/category/category_description');

?>
<?php if ($_category_desc == "main_column" && $_name = $block->getCurrentCategory()->getName()) : ?>
    <div class="category-name">
        <?php echo $this->helper('Magento\Catalog\Helper\Output')->categoryAttribute($block->getCurrentCategory(), $_name, 'description') ?>
    </div>
<?php endif; ?>
