<?php
/**
 * Zitec_Dpd – shipping carrier extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Zitec
 * @package    Zitec_Dpd
 * @copyright  Copyright (c) 2014 Zitec COM
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software
 *   License (OSL 3.0)
 */

namespace Zitec\Dpd\Block\Adminhtml\PrintShippingLabel\Sales\Order\Shipment;

/**
 *
 * @category   Zitec
 * @package    Zitec_Dpd
 * @author     Zitec COM <magento@zitec.ro>
 */
class View extends \Magento\Shipping\Block\Adminhtml\View
{

    /**
     * @var \Magento\Backend\Helper\Data
     */
    protected $backendHelper;

    public function _construct()
    {
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();

        $this->registry = $objectManager->get(\Magento\Framework\Registry::class);
        $this->backendHelper = $objectManager->get(\Magento\Backend\Helper\Data::class);

        if ($this->_hasPdfShippingLabel()) {
            $this->addButton('zitec_print_shipping_label', [
              'label'   => __('Print Shipping Labels'),
              'onclick' => "setLocation('{$this->_getPrintShippingLabelsUrl()}')",
            ]);
        }

        return parent::_construct(); // TODO: Change the autogenerated stub
    }

    /**
     * @return bool
     */
    protected function _hasPdfShippingLabel()
    {
        return $this->getShipment()->getShippingLabel() ? true : false;
    }

    /**
     *
     * @return string
     */
    protected function _getPrintShippingLabelsUrl()
    {
        return $this->backendHelper->getUrl('zitec_printshippinglabel/adminhtml_index/printshippinglabels',
          ['shipment_id' => $this->getShipment()->getId()]);
    }
}
