<?php
/**
 * Zitec_Dpd – shipping carrier extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Zitec
 * @package    Zitec_Dpd
 * @copyright  Copyright (c) 2014 Zitec COM
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Zitec\Dpd\Block\Adminhtml\Tablerate;

use Magento\Backend\Block\Template\Context;
use Magento\Backend\Block\Widget\Grid\Column;
use Magento\Backend\Block\Widget\Grid\Extended as ExtendedGrid;
use Zitec\Dpd\Model\Mysql4\Tablerate\Collection;

/**
 *
 * @category   Zitec
 * @package    Zitec_Dpd
 * @author     Zitec COM <magento@zitec.ro>
 */
class Grid extends ExtendedGrid
{

    /**
     *
     * @var array
     */
    protected $_map = null;

    /**
     * @var \Zitec\Dpd\Model\Mysql4\Tablerate\Collection
     */
    protected $tablerateCollection;

    /**
     * @var \Zitec\Dpd\Model\Tablerate\Source\Website
     */
    protected $tableRatesSourceWebsite;

    /**
     * @var \Magento\Directory\Model\Config\Source\CountryFactory
     */
    protected $directoryConfigSourceCountry;

    /**
     * @var \Magento\Store\Model\StoreManagerInterface
     */
    protected $storeManager;

    /**
     * @var \Zitec\Dpd\Helper\Tablerate\Data
     */
    protected $tableRatesHelper;
    /**
     * @var \Zitec\Dpd\Model\Mysql4\Tablerate
     */
    private $tablerateModelResource;

    public function _construct()
    {
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();

        $this->backendHelper = $objectManager->get(\Magento\Backend\Helper\Data::class);
        $this->tablerateModelResource = $objectManager->get(\Zitec\Dpd\Model\Mysql4\Tablerate::class);
        $this->tablerateCollection = $objectManager->get(Collection::class);
        $this->tableRatesSourceWebsite = $objectManager->get(\Zitec\Dpd\Model\Tablerate\Source\Website::class);
        $this->directoryConfigSourceCountry = $objectManager->get(\Magento\Directory\Model\Config\Source\Country::class);
        $this->storeManager = $objectManager->get(\Magento\Store\Model\StoreManagerInterface::class);
        $this->tableRatesHelper = $objectManager->get(\Zitec\Dpd\Helper\Tablerate\Data::class);


        $this->_map = $this->tablerateModelResource->getLogicalDbFieldNamesMap();

        $this->setId('zitec_tablerates_tablerateGrid');
        $this->setDefaultSort($this->_map['pk']);
        $this->setDefaultDir('DESC');
        $this->setSaveParametersInSession(true);
        $this->setUseAjax(true);

        parent::_construct(); // TODO: Change the autogenerated stub
    }

    protected function _prepareCollection()
    {
        $this->_prepareColumns();
        $this->_prepareMassaction();

        $this->setCollection($this->tablerateCollection);

        return parent::_prepareCollection();
    }

    protected function _prepareColumns()
    {
        $storeId = (int)$this->getRequest()->getParam('store', 0);
        $store = $this->storeManager->getStore($storeId);

        $this->addColumn('tablerate_id', array(
            'header' => __('ID'),
            'align'  => 'right',
            'width'  => '50px',
            'index'  => $this->_map['pk'],
        ));


        $this->addColumn('website', array(
            'header'       => __('Website'),
            'index'        => $this->_map['website_id'],
            'default'      => '',
            'type'         => 'options',
            'options'      => $this->tableRatesSourceWebsite->getWebsites(),
            'filter_index' => "main_table.{$this->_map['website_id']}"
        ));


        $this->addColumn('dest_country_id', array(
            'header'       => __('Destination Country'),
            'align'        => 'left',
            'index'        => $this->_map['dest_country_id'],
            'filter_index' => "main_table.{$this->_map['dest_country_id']}",
            'type'         => 'options',
            'options'      => $this->getCountryOptions(),
        ));

        $this->addColumn('dest_region', array(
            'header'       => __('Dest Region/State'),
            'align'        => 'left',
            'index'        => 'dest_region_name',
            'filter_index' => 'region_table.default_name',
            //'filter'       => 'zitec_tablerates/adminhtml_widget_grid_column_filter_region',
            'filter'       => \Zitec\Dpd\Block\Adminhtml\Tablerate\Widget\Grid\Column\Filter\Region::class,
            'default'      => '*',
        ));


        $this->addColumn('dest_zip', array(
            'header'  => __('Destination Zip/Postal Code'),
            'align'   => 'left',
            'index'   => $this->_map['dest_zip'],
            'default' => '*',
        ));

        $this->addColumn('method', array(
            'header'       => __('Service'),
            'align'        => 'left',
            'index'        => $this->_map['method'],
            'filter_index' => "main_table.{$this->_map['method']}",
            'type'         => 'options',
            'options'      => $this->tableRatesHelper->getMethodOptions(),
            'width'        => 150,
        ));

        if ($this->tableRatesHelper->supportsProduct()) {
            $this->addColumn('product', array(
                'header'       => __('Product'),
                'align'        => 'left',
                'index'        => $this->_map['product'],
                'filter_index' => "main_table.{$this->_map['product']}",
                'type'         => 'options',
                'options'      => $this->tableRatesHelper->getProductOptions(),
                'width'        => 150,
            ));
        }


        $this->addColumn('weight_and_above', array(
            'header'                    => __('Weight (and above)'),
            'index'                     => 'weight_and_above',
            'filter_condition_callback' => array($this, '_weightAndAboveFilter'),
            'default'                   => '*',
            'type'                      => 'number'
        ));

        if ($this->tableRatesHelper->supportsPriceVsDest()) {
            $this->addColumn('price_and_above', array(
                'header'                    => __('Price (and above)'),
                'align'                     => 'left',
                'index'                     => 'price_and_above',
                'filter_condition_callback' => array($this, '_priceAndAboveFilter'),
                'type'                      => 'price',
                'currency_code'             => $store->getBaseCurrency()->getCode(),
                'default'                   => '*',
            ));
        }

        $this->addColumn('is_enabled', array(
            'header'  => __('Enabled'),
            'align'   => 'left',
            'index'   => 'is_enabled_grid',
            'filter'  => false,
            'type'    => 'options',
            'options' => array(0 => __('No'), 1 => __('Yes')),
        ));

        $this->addColumn('shipping_price', array(
            'header'        => __('Shipping Price'),
            'align'         => 'left',
            'index'         => 'shipping_price_grid',
            'filter_index'  => "main_table.{$this->_map['price']}",
            'type'          => 'price',
            'currency_code' => $store->getBaseCurrency()->getCode(),
            'default'       => '',
        ));


        if ($this->tableRatesHelper->supportsMarkup()) {
            $this->addColumn('shipping_percentage', array(
                'header'       => __('Shipping Price %'),
                'align'        => 'left',
                'index'        => 'shipping_percentage_grid',
                'filter_index' => "main_table.{$this->_map['price']}",
                'type'         => 'number',
                'default'      => ''
            ));

            $this->addColumn('addition_amount', array(
                'header'        => __('Addition Price'),
                'align'         => 'left',
                'index'         => 'addition_amount_grid',
                'filter_index'  => "main_table.{$this->_map['price']}",
                'type'          => 'price',
                'currency_code' => $store->getBaseCurrency()->getCode(),
            ));

        }


        if ($this->tableRatesHelper->supportsCashOnDelivery()) {
            $this->addColumn('cod_surcharge_price', array(
                'header'        => __('COD Surcharge'),
                'align'         => 'left',
                'index'         => 'cod_surcharge_price',
                'filter_index'  => "main_table.{$this->_map['cashondelivery_surcharge']}",
                'type'          => 'price',
                'currency_code' => $store->getBaseCurrency()->getCode(),
            ));

            $this->addColumn('cod_surcharge_percentage', array(
                'header'       => __('COD Surcharge %'),
                'index'        => 'cod_surcharge_percentage',
                'filter_index' => "main_table.{$this->_map['cashondelivery_surcharge']}",
                'type'         => 'number',
            ));

            if ($this->tableRatesHelper->supportsCodMinSurcharge()) {
                $this->addColumn('cod_min_surcharge', array(
                    'header'        => __('COD Min. Surcharge'),
                    'index'         => $this->_map['cod_min_surcharge'],
                    'filter_index'  => "main_table.{$this->_map['cod_min_surcharge']}",
                    'type'          => 'price',
                    'currency_code' => $store->getBaseCurrency()->getCode(),
                ));
            }
        }


        return parent::_prepareColumns();
    }

    protected function _prepareMassaction()
    {
        $this->setMassactionIdField($this->_map['pk']);
        $this->getMassactionBlock()->setFormFieldName('tablerates');
        $this->getMassactionBlock()->addItem('delete', array(
            'label'   => __('Delete'),
            'url'     => $this->getUrl('*/*/massDelete', array("carrier" => $this->tableRatesHelper->getCarrierCode())),
            'confirm' => __('Are you sure?')
        ));

        return $this;
    }

    public function getGridUrl()
    {
        return $this->getUrl('*/*/grid', array('_current' => true, '_query' => array("carrier" => $this->tableRatesHelper->getCarrierCode())));
    }

    public function getRowUrl($row)
    {
        return $this->getUrl('*/*/edit', array('tablerate_id' => $row->getId(), "carrier" => $this->tableRatesHelper->getCarrierCode()));
    }

    /**
     * Get country options
     *
     * @return array
     */
    public function getCountryOptions()
    {
        $options   = array();
        $countries = $this->directoryConfigSourceCountry->toOptionArray(false);
        if (isset($countries[0])) {
            $countries[0] = array('value' => '0', 'label' => '*',);
        }
        foreach ($countries as $country) {
            $options[$country['value']] = $country['label'];
        }

        return $options;
    }

    /**
     *
     * @param \Zitec\Dpd\Model\Mysql4\Tablerate\Collection $collection
     * @param type Mage_Adminhtml_Block_Widget_Grid_Column
     *
     * @return \Zitec_Dpd_Block_Adminhtml_Tablerate_Grid
     */
    protected function _weightAndAboveFilter($collection, $column)
    {
        return $this->_weightPriceAndAboveFilter($collection, $column, false);
    }

    /**
     *
     * @param \Zitec\Dpd\Model\Mysql4\Tablerate\Collection $collection
     * @param \Magento\Backend\Block\Widget\Grid\Column $column
     *
     * @return \Zitec\Dpd\Block\Adminhtml\Tablerate\Grid
     */
    protected function _priceAndAboveFilter($collection, $column)
    {
        return $this->_weightPriceAndAboveFilter($collection, $column, true);
    }

    /**
     *
     * @param \Zitec\Dpd\Model\Mysql4\Tablerate\Collection $collection
     * @param \Magento\Backend\Block\Widget\Grid\Column $column
     * @param boolean $priceVsDest
     *
     * @return \Zitec\Dpd\Block\Adminhtml\Tablerate\Grid
     */
    protected function _weightPriceAndAboveFilter(
        Collection $collection,
        Column $column,
        $priceVsDest = false
    ) {

        if ($priceVsDest && !$this->tableRatesHelper->supportsPriceVsDest()) {
            return $this;
        }

        $value = $column->getFilter()->getValue();
        if (!is_array($value)) {
            return $this;
        }


        $from = isset($value['from']) ? $value['from'] : false;
        $to   = isset($value['to']) ? $value['to'] : false;

        if ($from === false && $to === false) {
            return $this;
        }

        $select = $collection->getSelect();
        if ($from !== false) {
            $select->where(" main_table.{$this->_map['weight_price']} >= ? ", $from);
        }


        if ($to !== false) {
            $select->where(" main_table.{$this->_map['weight_price']} <= ? ", $to);
        }

        $select->where(" main_table.{$this->_map['price_vs_dest']} = ? ", $priceVsDest ? 1 : 0);

        return $this;
    }
}
